name: nukePlugin
version: '1.3'
main: epin.nukePlugin.nukePlugin
api-version: '1.21'
authors: [ Ep1n ]
description: adds nukes and uranium and stuff idrk
commands:
  gimme:
    description: Old testing command due to paper bug. DO NOT type "/gimme OPERATOR_STATUS" idk how to turn it off

